### ISSUE TITLE
BUG Windows version of Nginx

### ISSUE THREAD

**Issue by vsin123** [nginx/nginx#118]
On the Windows version of Nginx, there is a limit of 1024 due to the maximum number of file access handles allowed. When the traffic volume is high, this limit can prevent the server from responding, resulting in the error: 'maximum number of descriptors supported by select() is 1024 while waiting for request.

The download address for Nginx on Windows is: http://nginx-win.ecsds.eu/download/.

I hope the official team addresses the limitation issue regarding the file access handle count of 1024 in the Windows version.

Feel free to adjust as needed!

**Comment by dfengpo** [comment]
<img width="286" alt="nginx 400" src="https://github.com/user-attachments/assets/b09f1a84-4c9c-425f-9e76-66cea7a5da41">

When I upload a mp3 file from device, I get this error.
device get *** select timeout or error *** error
![image](https://github.com/user-attachments/assets/e760128f-23c3-4037-98f3-647a8dd5056a)

**Comment by pluknet** [comment]
The limit corresponds to FD_SETSIZE set in official binary builds.
