### ISSUE TITLE
upload a mp3 file get http 400 error on nginx accect.log

### ISSUE THREAD

**Issue by dfengpo** [nginx/nginx#119]
This is my conf
http {
	sendfile on; 
        tcp_nodelay on;        
        keepalive_timeout  1800; 
	large_client_header_buffers 9999 9999k;
	client_max_body_size    100M;
	client_body_buffer_size 100M;
	proxy_connect_timeout   120s;
	proxy_send_timeout 120s; 
	proxy_read_timeout 120s; 
	proxy_buffers           9999 9999k;

server {
   listen 80;
 
   location / {
       proxy_pass XXX
       proxy_http_version 1.1;
       proxy_set_header   Upgrade $http_upgrade;
       proxy_set_header   Connection keep-alive;
       proxy_set_header   Host $http_host;
       proxy_cache_bypass $http_upgrade;
       proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header   X-Forwarded-Proto $scheme;
       proxy_set_header   X-Real-IP $remote_addr;
   }
}

When I upload a mp3 file from device, I get this error on accect.log
<img width="286" alt="nginx 400" src="https://github.com/user-attachments/assets/b09f1a84-4c9c-425f-9e76-66cea7a5da41">

And device error log
device get *** select timeout or error *** error
![image](https://github.com/user-attachments/assets/e760128f-23c3-4037-98f3-647a8dd5056a)

This my debug log
![image](https://github.com/user-attachments/assets/b720a45b-dcbd-4c58-bba4-334cbdadafb4)

**Comment by arut** [comment]
According to the error.log, the client (device) closed the socket before sending the entire file. It's hard to tell why it did so and what kind of timeout is that. Your nginx log is missing timestamps, which is why there's no way to tell whether the upload was indeed so slow that the client gave up.

**Comment by Maryna-f5** [comment]
Thanks for reporting this issue, @dfengpo.

We don't have sufficient information to proceed with further troubleshooting. Closing this issue for now. 
Please reopen the issue if you have more details about this problem.

**Comment by rea-leaf** [comment]
Has this problem been solved? I also encountered a similar problem @dfengpo
