### ISSUE TITLE
avoid crash of nginx server if ssl file not found

### ISSUE THREAD

**Issue by eldoy** [nginx/nginx#122]
I have lots of sites running on a server, and today NGINX decided to completely crash because a SSL certificate file was missing taking down all my sites. Is there a way to avoid that? If not, why does it work like that? It's a really bad design decision.

The missing file should be a WARNING and not prevent all sites from loading.

**Comment by viktorberezikov** [comment]
Dear @eldoy,

I assume you mean the inability to run NGINX if the file specified with the `ssl_certificate` directive does not exist.
The certificate file is a part of the configuration. If this file is missing, it is the `emerg` level error. Because you cannot run virtual servers that should support SSL but do not have a certificate.
Therefore, this is not a crash. This is expected behavior for a misconfiguration.

I would recommend using the following command for a safe reload:
`nginx -t && service nginx reload`
This command checks the configuration before reloading.

**Comment by eldoy** [comment]
I know, but I just think it's really unnecessary to crash the server because of misconfiguration. Why don't you just skip the failing configuration with a warning? Or is there an option like`skip_on_fail` or something?

**Comment by oxpa** [comment]
@eldoy what were exact commands resulting in the "crash"?

**Comment by eldoy** [comment]
@oxpa Trying to include an ssl certificate that doesn't exist in a single config crashes all of nginx instead of just skipping that config. I'm generating all nginx config programmatically because I have hundreds of sites, not having the option to skip bad configs is unnecessarily strict, whats the point?

**Comment by oxpa** [comment]
@eldoy nginx doesn't crash if you change configuration. Unless you explicitly stop it or attempt restarting (which also stops nginx). 
So to me it sounds like you are generating a faulty configuration, then stops nginx, then say nginx crashed.

First of all, stop generating faulty configuration. You can probably test file existence and skip servers with no certificates.
Secondly, don't stop nginx to reload a configuration. Use reload.

And finally, you can use a variable to configure an ssl certificate: http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate
Something like this will probably work:
```
set $my_cert = "/path/to/server.crt";
ssl_certificate $my_cert;
```
This will let nginx start with no "server.crt" but add some bigger overhead for the first handshake and some smaller overhead for all others.

**Comment by eldoy** [comment]
Did you generate that response with ChatGPT?

**Comment by oxpa** [comment]
No, I didn't. I spend some time typing it in manually.

Nginx needs ssl certificates on startup to avoid costly load operation on first handshake (and associated "random" delay).
You can use variables to configure ssl certificate and key paths. This removes requirement to have ssl cert in advance and introduces a delay associated with finding and loading a certificate on first handshake. 

Nginx works as intended and for now - there no plans to change this behavior.

**Comment by eldoy** [comment]
It seemed generated, you didn't really answer the question, I guess you wasted your time then. Crashing NGINX when only one config is faulty is a terrible design decision.
