### ISSUE TITLE
Ubuntu 24.04.1 nginx make problem

### ISSUE THREAD

**Issue by bojansimicmb** [nginx/nginx#128]
When trying to build nginx on Ubuntu 24.04.1 I have the following error:
Configure command succeeds without any issue and then make command fails. Tried Stable version 1.26 and latest Mainline 1.27.1

# Your nginx debug log here
make -f objs/Makefile
make[1]: Entering directory '/root/nginx-1.27.1'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I objs \
	-o objs/src/core/nginx.o \
	src/core/nginx.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I objs \
	-o objs/src/core/ngx_log.o \
	src/core/ngx_log.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I objs \
	-o objs/src/core/ngx_palloc.o \
	src/core/ngx_palloc.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I objs \
	-o objs/src/core/ngx_array.o \
	src/core/ngx_array.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I objs \
	-o objs/src/core/ngx_list.o \
	src/core/ngx_list.c
<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:565: objs/src/core/ngx_list.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:558: objs/src/core/ngx_array.o] Error 1
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:551: objs/src/core/ngx_palloc.o] Error 1
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:544: objs/src/core/ngx_log.o] Error 1
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:537: objs/src/core/nginx.o] Error 1
make[1]: Leaving directory '/root/nginx-1.27.1'
make: *** [Makefile:10: build] Error 2

or share the debug log in [gist](https://gist.github.com/).

**Comment by oxpa** [comment]
I guess you are trying to build a package using debhelper? can you share your rules files? Are these self-written?
You should probably do a change like pkg-oss has: https://github.com/nginx/pkg-oss/blob/master/debian/debian/nginx.rules.in#L7

**Comment by bojansimicmb** [comment]
I'm downloading nginx from here : https://nginx.org/en/download.html
Unpacking archive and then using ./configure with all the properties and then running make, then this error happens.

**Comment by oxpa** [comment]
@bojansimicmb could you please share the configure commands and it's output?
I can't reproduce the issue using "ubuntu:24.04" container. I do the following:
```
apt-get install wget gcc less libz-dev libpcre3-dev libssl-dev make
wget https://nginx.org/download/nginx-1.27.1.tar.gz
tar -xf nginx-1.27.1.tar.gz
cd nginx-1.27.1
./configure --with-compat
make -j
```

**Comment by bojansimicmb** [comment]
apt install zlib1g zlib1g-dev libpcre3 libpcre3-dev libssl-dev build-essential -y

git clone https://github.com/leev/ngx_http_geoip2_module.git

add-apt-repository ppa:maxmind/ppa

apt install libmaxminddb0 libmaxminddb-dev mmdb-bin geoipupdate

cd nginx-1.27.1

./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' --add-dynamic-module=../ngx_http_geoip2_module/

make -j 

I have been using these steps on Ubuntu 22.04 from the beginning and no issue at all.

EDIT: https://gist.github.com/bojansimicmb/eaca59dd433727910c539f949973c3c0#file-gistfile1-txt

**Comment by oxpa** [comment]
dont use '-Wp,-D_FORTIFY_SOURCE=2' in the command. Either drop it or increase the level.
It's a change in ubuntu 24: https://wiki.ubuntu.com/ToolChain/CompilerFlags

**Comment by bojansimicmb** [comment]
It works. Thank you!
