### ISSUE TITLE
Having trouble with Kemo app

### ISSUE THREAD

**Issue by Bella2017ops** [nginx/nginx#158]
Having trouble with Kemo app

_Originally posted by @Bella2017ops in https://github.com/nginx/nginx/discussions/157_

**Comment by Bella2017ops** [comment]
I'm still can't find Kemo account and app connection

**Comment by Bella2017ops** [comment]
Can't find Kemo application

**Comment by Bella2017ops** [comment]
Please send instructions to find Kemo streeming system

**Comment by ninaforsyth** [comment]
Contact Kemo, not us.
