### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [nginx/nginx#161]
File:
/src/event/ngx_event_connectex.c line 42
Code:
if (nconnects < NGX_MAX_PENDING_CONN) {
            pending_connects[--nconnects] = c;
            LeaveCriticalSection(&connect_lock);
            if (SetEvent(pending_connect_event) == 0) {
                ngx_log_error(NGX_LOG_ALERT, c->log, ngx_errno,
                              "SetEvent() failed");
                return NGX_ERROR;
            break; // <-- unreachable
        }

**Comment by arut** [comment]
This file is not compiled and will be removed.
