### ISSUE TITLE
using same cache in two server{} result in duplicate headers and "has too long header" errors

### ISSUE THREAD

**Issue by pva** [nginx/nginx#168]
### Environment

nginx -V
nginx version: nginx/1.25.4
built by gcc 14.2.1 20240817 (Gentoo 14.2.1_p20240817 p4) 
built with OpenSSL 3.0.13 30 Jan 2024
TLS SNI support enabled
configure arguments: --prefix=/media/oss/nginx/ --with-http_ssl_module --with-http_v2_module --with-threads --with-file-aio

Linux x1 6.10.4-gentoo-dist #1 SMP PREEMPT_DYNAMIC Mon Aug 12 15:46:32 -00 2024 x86_64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz GenuineIntel GNU/Linux

### Description

Whenever I use the same cache in two virtual hosts (server{}) I get duplicate headers in reply. So here is the relevant part of nginx config:

```
proxy_cache_path /tmp/nginx/1 keys_zone=ram_chunks1:64m levels=1:1 max_size=3g inactive=20m manager_files=1000 loader_files=1000;
proxy_cache_valid 200 120m;
proxy_cache_valid 404 1m;

server {
    listen 8081;
    server_name domain.ru;

    access_log /media/oss/nginx/logs/domain.ru.access_log main;
    error_log /media/oss/nginx/logs/domain.ru.error_log info;

    location / {
        proxy_cache ram_chunks1;
        # We use same key for every request
        proxy_cache_key "random";
        proxy_buffering on;
        proxy_cache_lock off;
        proxy_cache_valid 200 10s;
        # Allows starting a background subrequest to update an expired cache item,
        # while a stale cached response is returned to the client.
        # Required to avoid flooding upstream with update requests.
        proxy_cache_use_stale updating timeout invalid_header error;
        proxy_cache_background_update on;

        add_header X-Cache-Status "LIVE cache on server listening on 8081 port: ${upstream_cache_status}" always;
        add_header X-Random-Header "Header from server listening on 8081 port";
        proxy_pass http://unix:/tmp/nginx_dvr_proxy_oserver_cdn.sock;
    }
}

server {
    listen unix:/tmp/nginx_dvr_proxy_oserver_cdn.sock default_server;

    access_log off;
    error_log /media/oss/nginx/logs/domain.ru_sock.error_log info;

    location / {
        proxy_cache ram_chunks1;
        proxy_cache_key "random";
        proxy_buffering on;
        proxy_cache_lock on;
        proxy_cache_valid 200 10s;
        proxy_cache_use_stale updating timeout invalid_header error;
        proxy_cache_background_update on;

        add_header X-Cache-Status "LIVE cache on server listening on unix socket: ${upstream_cache_status}" always;
        add_header X-Random-Header "Just random header";
        # Backend always returns http 200
        proxy_pass http://127.0.0.1:10101;
    }
}

```

Same cache - ram_chunks1 is used in both server {} configurations and one server proxy_pass'e requests to another. This proxy_pass simulates the situation when the same request comes to different servers at the same time. To make the situation even more pronounced on 127.0.0.1:10101 I've started a service that makes replies with a 10s delay.

Now at the parallel console, I run in-cycle requests to nginx:

`while true; do curl -v 127.0.0.1:8081/test; done`

Quite fast I can see in output duplicate X-Cache-Status and X-Random-Header headers:

```
* Connection #0 to host 127.0.0.1 left intact
*   Trying 127.0.0.1:8081...
* Connected to 127.0.0.1 (127.0.0.1) port 8081
> GET /test HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/8.8.0
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 12 Sep 2024 10:39:43 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Keep-Alive: timeout=20
< X-Lfstrm-Ms-Host: x1
< X-Lfstrm-Ms-Name: slowpoke
< X-Lfstrm-Ms-Version: master-4c5ea8a-2024.08.22-09:51
< X-Cache-Status: LIVE cache on server listening on unix socket: MISS
< X-Random-Header: Just random header
< X-Cache-Status: LIVE cache on server listening on unix socket: UPDATING
< X-Random-Header: Just random header
< X-Cache-Status: LIVE cache on server listening on unix socket: UPDATING
< X-Random-Header: Just random header
< X-Cache-Status: LIVE cache on server listening on 8081 port: HIT
< X-Random-Header: Header from server listening on 8081 port
< 
Thank you for your patience!
```

So is this duplication expected? In production systems we had to increase proxy_buffer_size to 128k since otherwise we've got **has too long header** error in error_log.

**Comment by jo-carter** [comment]
This isn't a bug, you are double proxying and are simply adding the header twice, once in each 'pass' through nginx...

**Comment by viktorberezikov** [comment]
All in all, you get the behavior you configured. First, you use the same cache key for each request. At the same time, you pass each request through two virtual servers with the same cache key. In addition, you allow the usage of a stale cached response. Therefore, it turns out that during the delay time, the second server gives the responses read from the cache written by the first server. That's why you can see headers added by the second server several times.

**Comment by Maryna-f5** [comment]
Thanks @viktorberezikov for providing clarifications!
