### ISSUE TITLE
access_log doesn't work with error_page

### ISSUE THREAD

**Issue by x90nik** [nginx/nginx#173]
### Environment

  - `nginx -V`
> nginx version: nginx/1.26.2
built by cl 16.00.30319.01 for 80x86
built with OpenSSL 3.0.14 4 Jun 2024
TLS SNI support enabled
configure arguments: --with-cc=cl --builddir=objs.msvc8 --with-debug --prefix= --conf-path=conf/nginx.conf --pid-path=logs/nginx.pid --http-log-path=logs/access.log --error-log-path=logs/error.log --sbin-path=nginx.exe --http-client-body-temp-path=temp/client_body_temp --http-proxy-temp-path=temp/proxy_temp --http-fastcgi-temp-path=temp/fastcgi_temp --http-scgi-temp-path=temp/scgi_temp --http-uwsgi-temp-path=temp/uwsgi_temp --with-cc-opt=-DFD_SETSIZE=1024 --with-pcre=objs.msvc8/lib/pcre2-10.39 --with-zlib=objs.msvc8/lib/zlib-1.3.1 --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_stub_status_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_slice_module --with-mail --with-stream --with-stream_realip_module --with-stream_ssl_preread_module --with-openssl=objs.msvc8/lib/openssl-3.0.14 --with-openssl-opt='no-asm no-tests -D_WIN32_WINNT=0x0501' --with-http_ssl_module --with-mail_ssl_module --with-stream_ssl_module
  - `uname -a`
> Windows 10 - CYGWIN_NT-10.0-19045 DESKTOP-ABCN0QC 3.5.3-1.x86_64 2024-04-03 17:25 UTC x86_64 Cygwin

### Description

I specified `access_log off;` in `/favicon.ico` location. It works fine until I use `error_page 404 /error/404.html;`.
Actually, by using `error_page` directive, `access_log off` will not work.

Sent a request via `curl -X GET 127.0.0.1:80/favicon.ico`.
And you will see `127.0.0.1 - - [13/Sep/2024:05:16:10 +0200] "GET /favicon.ico HTTP/1.1" 404` log in `access.log`.

- [x] The bug is reproducible with the latest version of nginx
- [x] The nginx configuration is minimized to the smallest possible
to reproduce the issue and doesn't contain third-party modules

#### nginx configuration

- nginx.conf
```
worker_processes 1;
daemon off;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    include server/*.conf;
}
```
- server/localhost.conf
```
server {
    listen 80;
    server_name localhost;
    root html;

    location / {
        index index.html;
    }

    # Icon
    location /favicon.ico {
        access_log off;
    }

    # Error page
    error_page 404 /error/404.html;

    location /error {
        root html;
        internal;
    }
}
```

- directory structure

```
nginx/
├─── nginx.exe
│
├─── html/
├─── logs/
│
└─── conf/
     ├─── nginx.conf
     │
     └─── server/
          └─── localhost.conf
```

**Comment by viktorberezikov** [comment]
I would recommend reading about the `error_page` directive [here](https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page).
In your configuration, there is a redirect to `location /error` for responses with the 404 code. Which does not contain the `access_log off;` directive.
This is the expected behavior for the configuration.

**Comment by x90nik** [comment]
@viktorberezikov
That's true, thank you for the response.
```cnf
location /error {
    access_log off;
    root html;
    internal;
}
```
