### ISSUE TITLE
Support HTTP status code in access_log

### ISSUE THREAD

**Issue by x90nik** [nginx/nginx#175]
### Describe the feature you'd like to add to nginx

In order to separate the logs to different endpoints, it's a good idea to support HTTP status code like `error_page` directive.
```cnf
# nginx.conf

user nginx;
error_log /var/www/log/error.log warn;

http {
    log_format main '$status -> "$request"';

    # Keep the access_log's current functionality.
    access_log /var/www/log/access.log main;

    include /etc/nginx/http.d/example.com.conf;
}
```
```cnf
# example.com.conf

server {
    listen 443 ssl;

    access_log 503 off;
    access_log 500 /var/log/nginx/5xx.log main;
    access_log 401 403 404 syslog:server=unix:/var/log/nginx/4xx.sock,nohostname;
}
```

### Describe the problem this feature solves

Separation of logs.

### Additional context

Keep the `access_log`'s current functionality.
I except these at the end:
```cnf
access_log /var/log/nginx/error.log main;
access_log 403 off;
access_log 404 /var/log/nginx/404.log main;
access_log 500 503 /var/log/nginx/5xx.log main;
```

**Comment by x90nik** [comment]
In addition to the [original post](https://github.com/nginx/nginx/issues/175#issue-2523832200), another good option could be like this:
```cnf
# Turn off logs for 401 and 403 HTTP status code.
access_log 401 403 off;
```

**Comment by lcrilly** [comment]
Please see the `if` parameter to the `access_log` directive
https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log

This provides a conditional logging facility that meets all the above requirements.

**Comment by x90nik** [comment]
Thank you for the fast response.

```cnf
# nginx.conf

user nginx;
error_log /var/log/nginx/error.log warn;

http {
    log_format main '$status -> "$request"';

    map $status $loggable {
        403 1;
        default 0;
    }

    include /etc/nginx/http.d/example.com.conf;
}
```
```cnf
# example.com.conf

server {
    listen 443 ssl;

    access_log logs/403.log main if=$loggable;
}
```
