### ISSUE TITLE
Memory Leak in upstreams when combining high weight and consistent(ketama) hash

### ISSUE THREAD

**Issue by sbstnpl1** [nginx/nginx#191]
### Environment
Linux nginx1 5.10.0-32-amd64 #1 SMP Debian 5.10.223-1 (2024-08-10) x86_64 GNU/Linux
reproducible with
- nginx/1.26.0,
- ngnx/1.27.1
- nginx-plus-r32-p1 

### Description
- [X] The bug is reproducible with the latest version of nginx
- [X] The nginx configuration is minimized to the smallest possible

#### nginx configuration
absolutely minimal (debian) configuration. Just have modified:
```
location / {
  proxy_pass http://upstr;
}
```
```
upstream upstr {
	hash $cookie_chronosessid consistent;
	server 10.0.10.31:8080 weight=1000000;
	server 10.0.10.32:8080;
}
```

Then (re)start nginx and see how nginx begins to grab gigabytes of memory within seconds and probably beeing crashed by oom-killer.

Either lowering `weight` significantly or not using `consistent` works around the issue. But in combination, these two values are poison. 
We have also observed that the effect is even greater when HTTP traffic is processed.

**Comment by viktorberezikov** [comment]
I would suggest reading the documentation about the `consistent` parameter for the `hash` directive:
https://nginx.org/en/docs/http/ngx_http_upstream_module.html#hash
Briefly, the consistent hash requires memory. If you increase the number of peers or their weights, you need more memory. This is not a leak. The memory allocation expected by the configuration is allocated.

**Comment by sbstnpl1** [comment]
Hi @viktorberezikov,
thank you for you suggestion to read the documentation. Be confident I did. Don't know where you are reading, but your linked section do not mention memory allocation, especially not in connection with weighting.
Nevermind. If if you guys think it's great that an idle web server may allocate 30gig of memory just because some weights are set, I can only apologize for the disturbance. Feel free to close this issue.

**Comment by arut** [comment]
Regarding memory consumption. Here's the code that allocates memory:
https://github.com/nginx/nginx/blob/1a64c196a7d43f83a14fec20ce8936e599c92865/src/http/modules/ngx_http_upstream_hash_module.c#L314
Unlike round-robin, for ketama actual weight values matter in terms of memory consumption.

On a 64-bit system ketama table size is `weight * 160 * 24 = weight * 3840 bytes`. If weight is 1M, then nginx allocates 3.8G+ memory. It should not be 30G for just a single consistent hash balancer.

**Comment by kelunik** [comment]
@arut I've made another test on my local MacBook, the calculated numbers don't seem to match there, seems to be a bit less:

- Total weight of 1M consumed 2,39 GB of memory and required 20 seconds CPU time for initialization.
- Total weight of 10M consumed 23,85 GB of memory and required 3 minutes and 48 seconds of CPU time for initialization.

What we were actually trying to achieve with these high weights is a kind of fallback pool: Keep all upstreams in a single pool, but only use some of them (those with the high weights, others are "essentially off"). If there's no upstream with high weight available, distribute between those with low weight equally.

There are other ways to solve this, however, we still think modifying weights like that shouldn't result in explosion of initialization time and memory usage.

**Comment by viktorberezikov** [comment]
There are links in the documentation that describe the ketama algorithm for the consistent hash. To be clear, the consistency is achieved by generating and storing hashes for multiple points in memory. These points are placed on an imaginary circle and are chosen depending on the hash of the key for each request. By increasing the number of points, you increase the resources needed for the algorithm to operate.
In addition, I'm not quite sure why you are using the `hash` directive with the `consistent` parameter and heavy weights for your goal. It seems that the `backup` parameter of the `server` directive would work well for your goal.
More information here:
https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server

**Comment by sbstnpl1** [comment]
Hi @viktorberezikov ,
> In addition, I'm not quite sure why you are using the hash directive with the consistent parameter and heavy weights for your goal. It seems that the backup parameter of the server directive would work well for your goal.

No, this is not supported. Please see [documentation](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server) for `backup` parameter:
> The parameter cannot be used along with the hash, ip_hash, and random load balancing methods.

**Comment by viktorberezikov** [comment]
That's right, the proposed example involves removing the hash balancing method. If you wish to discuss options, I suggest asking in the Discussions section. This issue seems to be answered.
