### ISSUE TITLE
Cleanup of temporary files for client requests after request processing

### ISSUE THREAD

**Issue by PrinsFrank** [nginx/nginx#192]
### Describe the feature you'd like to add to nginx

As far as I can see in the documentation, the option to clean up temporary files only exists for directive `client_body_in_file_only` set to `clean`. <sup><a href="http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_in_single_buffer">1</a></sup>, but we don't have that setting configured.

Large request bodies are stored in the path configured with `client_body_temp_path`, but I don't see an option to automatically delete these after the request has been handled. <sup><a href="http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path">2</a></sup>

I don't think `client_body_in_file_only` should be used for this, but it could make sense to add a separate directive for this, or even set this as the default, right? Or am I missing a setting?

### Describe the problem this feature solves

We're running into issues where users upload large files. The request bodies are stored in a temporary file, but that temporary file never gets cleaned up, resulting in us running out of disk space. (To be clear, we don't have `client_body_in_file_only` configured.)

There are some older discussions on several forums where this is solved with tmpwatch or some other custom solution:
https://stackoverflow.com/questions/21484788/nginx-automated-tmp-cleanup
https://serverfault.com/questions/570052/nginx-temporary-files-cleanup-automatically

But some other sources say this should be the default behaviour. 

### Additional context

We do have `fastcg_request_buffering` enabled, that might be related?

**Comment by arut** [comment]
All nginx temporary files should be deleted automatically after request completion, unless it's explicitly disabled. This may not work properly if:
- the request takes a long time to complete; all this time the file will be on disk
- nginx worker is killed, in which case the file will never be deleted

Indeed `fastcgi_request_buffering` directive may result in creation of temporary files on disk and they should be automatically deleted, as stated above.

Please make sure nginx worker was not killed and the request which created the file has finished.

In case it's all ok, please [enable debug logging](https://nginx.org/en/docs/debugging_log.html) and find all lines in error.log related to a particular request body file that was created and never deleted. Those lines need to be analyzed.

**Comment by PrinsFrank** [comment]
Thanks for the extensive response and explanation of expected behaviour! I've been trying to reproduce the behavior we see here locally, but I'm unable to reproduce this currently. I'll close this issue here and contact our hosting provider. Thanks again for the help!
