### ISSUE TITLE
 Nginx-quic support multi-path transmission and connection migration

### ISSUE THREAD

**Issue by Alanliam** [nginx/nginx#197]
Does Nginx-quic support multi-path transmission and connection migration? If it is not supported, how long will it take to go online?

**Comment by arut** [comment]
nginx supports QUIC connection migration, but you need to enable [quic_bpf](https://nginx.org/en/docs/http/ngx_http_v3_module.html#quic_bpf) for it.
QUIC multi-path transmission is not supported.
