### ISSUE TITLE
NGINX Proxy Buffer related parameter configuration

### ISSUE THREAD

**Issue by CCTV-six** [nginx/nginx#199]
### CurrentBehavior

The 'warn' in the log report 'an upstream response is buffered to a temporary file' usually requires configuring the website's proxy buffer related parameters. However, for proxy buffer related parameters, how large should I configure them reasonably

### ExpectedBehavior

What is the reasonable configuration for proxy buffer related parameters

**Comment by arut** [comment]
Buffering response to a temp file is not an error and is a reasonable behavior when client is slower than proxied server and configured buffers are too small to keep the data in memory. If you want to avoid using temporary files, you can increase [proxy_buffers](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffers) up to a typical response size. This may be inappropriate for large responses. Another option ia to [disable](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering) buffering at all.
