### ISSUE TITLE
ESI System Manager does not take the updates after sending programing

### ISSUE THREAD

**Issue by BPUSIT** [nginx/nginx#206]
### Environment

Include the result of the following commands:

ESI System Manager Version: 45.0.1
(ESM) Middleware Version: 42.0.1
(ESM) Package Version: 1.1.0.12

### Description

ESI System Manager does not take the updates after sending programming
Data last pulled for USERIT on: Wednesday, February 22nd, 2023 07:43 AM

**Comment by Maryna-f5** [comment]
This is invalid issue
