### ISSUE TITLE
How do we set nginx.conf to support nginx-quic 0-rtt connection?

### ISSUE THREAD

**Issue by Alanliam** [nginx/nginx#214]
Below is my nginx.conf.
#user  nobody;
worker_processes  1;

error_log  logs/error.log  debug_event  debug_http debug_core;
daemon off;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    sendfile        on;
    #tcp_nopush     on;
    #keepalive_timeout  0;
    keepalive_timeout  65;
    #gzip  on;

server {
        listen 80;
        listen 443 ssl;
        listen [::]:443 ssl;
        
        listen 443 quic reuseport;
        listen [::]:443 quic reuseport;

        http3 on;
        http3_hq on;
        server_name  localhost;

        ssl_certificate /usr/local/nginx/cert/ca-cert.pem; 
        ssl_certificate_key /usr/local/nginx/cert/ca-key.pem;
        
        ssl_protocols TLSv1.3;
        add_header Alt-Svc 'h3=":443"; ma=86400';
        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        add_header X-protocol $server_protocol always;

        ssl_early_data on;
        ssl_session_tickets on;

        ssl_prefer_server_ciphers on; 
        ssl_session_timeout 5m;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256'; 

        location / {
            root   html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }
}

By using ./nginx -c /usr/local/nginx/conf/nginx.conf and curl -kv --http3 https://localhost:443/index.html ,I don't see the 0-rtt packet in wireshark.I wonder if there is anything wrong with my nginx.conf? Or what do I need to pay attention to?I am looking forward to your reply. I would appreciate it
![image](https://github.com/user-attachments/assets/b31a88a4-8a87-446f-93e4-a97831ee7311)

**Comment by arut** [comment]
First, make sure you are not using OpenSSL compatibility layer, which does not support 0-RTT, see a note [here](https://nginx.org/en/docs/http/ngx_http_v3_module.html). You need to link a library other than OpenSSL, for example BoringSSL.

**Comment by gulch** [comment]
Move `ssl_early_data on;` directive from "server" to "http" configuration section.

**Comment by Maryna-f5** [comment]
The question was answered, closing this issue.  
@Alanliam, if you have more questions, please start a discussion.
