### ISSUE TITLE
access_log within if out location context

### ISSUE THREAD

**Issue by par7133** [nginx/nginx#224]
Hello,

I find the constraint for the directive access_log inside if only under location quite limitating. I'm not sure if this constraint is due thinging to the security of the product. To be clear I don't see this extraordinary difference between to be in or out location in respect of security.

I was in the need to do something similar to this:

server {
  
   listen 80;
   listen [::]:80;

   if ($monitortool = 0) {
      access_log  5mode-com.log combined buffer=64k flush=10m;
   }

   [...]
}

Adding that true I could use the if option of access_log and in my case could be great. But considering that I could have more flags indicating to me if logging is due or not I find Nginx limitaiting myself.

Hope this helps.

-Dan

**Comment by jo-carter** [comment]
This functionality can be effectively achieved already through conditional access logs, ie the _if=condition_ argument of[ access_log directive.](https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log).

**Comment by Maryna-f5** [comment]
Suggestion was provided. Closing this issue.
