### ISSUE TITLE
access_log off; before on more access_log directive stop logging without generating exception

### ISSUE THREAD

**Issue by par7133** [nginx/nginx#227]
Hello,

A double access_log declaration under same server context seems saying Nginx to choose the first one listed.

The problem is that putted as such if, by example..

server {
access_log off;

[do something else]

access_log  myaccess-5mode-com.log combined buffer=64k flush=10m;

}

My advice given these condition Nginx should generate an exception to the admin as it silently doens't log anything more.

Thanks,

-Dan

**Comment by jo-carter** [comment]
This is intended behavior as per [documentation](https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log).
> The special value off cancels all access_log directives on the current level.

**Comment by par7133** [comment]
Thanks for the clarification. Though, it was not easy to grasp that also the following declarations get cancelled.

-Dan


> C4P!¥4n
> -------
>  C|_0Ud

Sep 30, 2024 08:18:47 jo-carter ***@***.***>:
