### ISSUE TITLE
nginx 1.26.x-1.27.x msys2 build error

### ISSUE THREAD

**Issue by tzrd** [nginx/nginx#246]
### Environment

nginx 1.26.x、1.27.x
msys2-x86_64-20240727

### Description

cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/win32 -I ../pcre2-10.44/src/ -I ../openssl-3.0.15/.openssl/include -I ../zlib-1.3.1 -I /usr/include/libxml2 -I objs \
        -o objs/src/event/quic/ngx_event_quic_connid.o \
        src/event/quic/ngx_event_quic_connid.c
In file included from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_connection.h:127:39: error: field 'udp' has incomplete type
  127 |     ngx_udp_connection_t              udp;
      |                                       ^~~
src/event/quic/ngx_event_quic.c: In function 'ngx_quic_input_handler':
src/event/quic/ngx_event_quic.c:434:15: error: invalid use of incomplete typedef 'ngx_udp_connection_t' {aka 'struct ngx_udp_connection_s'}
  434 |     b = c->udp->buffer;
      |               ^~
In file included from src/event/quic/ngx_event_quic_udp.c:11:
src/event/quic/ngx_event_quic_connection.h:127:39: error: field 'udp' has incomplete typemake[1]: *** [objs/Makefile:978: objs/src/event/quic/ngx_event_quic.o] Error 1
make[1]: *** Waiting for unfinished jobs....

  127 |     ngx_udp_connection_t              udp;
      |                                       ^~~
src/event/quic/ngx_event_quic_udp.c: In function 'ngx_quic_recvmsg':
src/event/quic/ngx_event_quic_udp.c:29:25: error: array type has incomplete element type 'struct iovec'
   29 |     struct iovec        iov[1];
      |                         ^~~
src/event/quic/ngx_event_quic_udp.c:30:25: error: storage size of 'msg' isn't known
   30 |     struct msghdr       msg;
      |                         ^~~
In file included from In file included from src/event/quic/ngx_event_quic_transport.c:10src/core/ngx_core.h:53:
,
                 from src/event/quic/ngx_event_quic_connection.h:127:39:src/event/quic/ngx_event_quic_udp.c:9 :
error: src/event/quic/ngx_event_quic_udp.c:66:34:field ' udperror: ' has incomplete type
  127 |     ngx_udp_connection_t              invalid application of 'udpsizeof' to incomplete type ';
      |                                       struct msghdr^~~'
   66 |         ngx_memzero(&msg, sizeof(
struct msghdr));
      |                                  ^~~~~~
src/core/ngx_string.h:88:57: note: in definition of macro 'ngx_memzero'
   88 | #define ngx_memzero(buf, n)       (void) memset(buf, 0, n)
      |                                                         ^
src/event/quic/ngx_event_quic_udp.c:85:13: error: implicit declaration of function 'recvmsg'; did you mean 'recv'? [-Wimplicit-function-declaration]
   85 |         n = recvmsg(lc->fd, &msg, 0);
      |             ^~~~~~~
      |             recv
src/event/quic/ngx_event_quic_udp.c:189:19: error: invalid use of incomplete typedef 'ngx_udp_connection_t' {aka 'struct ngx_udp_connection_s'}
  189 |             c->udp->buffer = &buf;
      |                   ^~
src/event/quic/ngx_event_quic_udp.c:198:23: error: invalid use of incomplete typedef 'ngx_udp_connection_t' {aka 'struct ngx_udp_connection_s'}
  198 |                 c->udp->buffer = NULL;
      |                       ^~
src/event/quic/ngx_event_quic_udp.c:30:25: error: unused variable 'msg' [-Werror=unused-variable]
   30 |     struct msghdr       msg;
      |                         ^~~
src/event/quic/ngx_event_quic_udp.c:29:25: error: unused variable 'iov' [-Werror=unused-variable]
   29 |     struct iovec        iov[1];
      |                         ^~~
cc1.exe: all warnings being treated as errors
make[1]: *** [objs/Makefile:992: objs/src/event/quic/ngx_event_quic_transport.o] Error 1
make[1]: *** [objs/Makefile:985: objs/src/event/quic/ngx_event_quic_udp.o] Error 1
In file included from src/event/quic/ngx_event_quic_protection.c:10:
src/event/quic/ngx_event_quic_connection.h:127:39: error: field 'udp' has incomplete type
  127 |     ngx_udp_connection_t              udp;
      |                                       ^~~
make[1]: *** [objs/Makefile:999: objs/src/event/quic/ngx_event_quic_protection.o] Error 1
In file included from src/event/quic/ngx_event_quic_frames.c:10:
src/event/quic/ngx_event_quic_connection.h:127:39: error: field 'udp' has incomplete type
  127 |     ngx_udp_connection_t              udp;
      |                                       ^~~
make[1]: *** [objs/Makefile:1006: objs/src/event/quic/ngx_event_quic_frames.o] Error 1
In file included from src/event/quic/ngx_event_quic_connid.c:10:
src/event/quic/ngx_event_quic_connection.h:127:39: error: field 'udp' has incomplete type
  127 |     ngx_udp_connection_t              udp;
      |                                       ^~~
make[1]: *** [objs/Makefile:1013: objs/src/event/quic/ngx_event_quic_connid.o] Error 1
make[1]: Leaving directory '/d/CppProject/ngx-ng-src/nginx-1.26.2'
make: *** [Makefile:10: build] Error 2

#### nginx configuration

./configure --prefix=../ngx-ng --with-select_module --with-poll_module --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module  --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --with-stream_realip_module --with-stream_geoip_module=dynamic --with-stream_ssl_preread_module --with-pcre=../pcre2-10.44 --with-openssl=../openssl-3.0.15 --with-zlib=../zlib-1.3.1 --with-pcre-jit --with-libatomic

**Comment by pluknet** [comment]
This is intentional because UDP functionality is not supported.
See http://nginx.org/en/docs/windows.html
