### ISSUE TITLE
Double Escaping in $ssl_client_s_dn

### ISSUE THREAD

**Issue by Jeswin-w** [nginx/nginx#255]
**Description**
I have a client certificate which has non English characters in the subject, when I use the attribute $ssl_client_s_dn of ngx_http_ssl_module the value is escaped twice.

actual value = "L=D'UNCONG\x5CC3\x5C89"

expected value = "L="D'UNCONG\xC3\x89"

can someone kindly advise me on what I did wrong, How can I avoid this.

not sure if this belongs here or the nginx_http_ssl_module, posted here as I couldn't find the modules repo

**Comment by jo-carter** [comment]
OP asked (and was given an answer) [here](https://serverfault.com/a/1166674).

Also just FYI @Jeswin-w custom logic in a [js_set](https://nginx.org/en/docs/http/ngx_http_js_module.html#js_set) function is good for this use-case by the way, if you are still looking for a workaround.
