### ISSUE TITLE
ngx_http_upstream_random_module.c:412

### ISSUE THREAD

**Issue by patch-work** [nginx/nginx#264]
Reporting this as a bug, but is a security vulnerability, and the Security section above does not return a submission page.

checking for OS
+ OpenBSD 7.6 amd64
checking for C compiler ... found
+ using Clang C compiler
+ clang version: 16.0.6
...
`ld: warning: ngx_http_upstream_random_module.c:412 (src/http/modules/ngx_http_upstream_random_module.c:412)(objs/src/http/modules/ngx_http_upstream_random_module.o:(ngx_http_upstream_get_random2_peer)): warning: random() may return deterministic values, is that what you want?`
...
Configuration summary
+ using PCRE2 library: /tmp/pcre2-10.44
+ using system OpenSSL library
+ using zlib library: /tmp/zlib-1.3.1

> openssl --version
OpenSSL 3.2.3 3 Sep 2024 (Library: OpenSSL 3.2.3 3 Sep 2024)

**Comment by jo-carter** [comment]
> Reporting this as a bug, but is a security vulnerability,

random() (ngx_random()) is used in this context as part of process for randomly selecting an upstream peer, it does not need to use a cryptographically secure random implementation.

**Comment by patch-work** [comment]
> random() (ngx_random()) is used in this context as part of process for randomly selecting an upstream peer, it does not need to use a cryptographically secure random implementation.

Is there a need for a warning then? 

I would still like to solve the problem.

**Comment by jo-carter** [comment]
@patch-work The warning is from the compiler (linker), not from NGINX.

**Comment by patch-work** [comment]
Yes, it is from the linker, and it is relative to an nginx source file.
