### ISSUE TITLE
Incorrect value of remote_addr variable when receiving bad request and when http listen proxy_protocol

### ISSUE THREAD

**Issue by skl256** [nginx/nginx#274]
### Environment

Docker, nginx:1.26.2-bookworm
```
nginx version: nginx/1.26.2
built by gcc 12.2.0 (Debian 12.2.0-14)
built with OpenSSL 3.0.11 19 Sep 2023 (running with OpenSSL 3.0.14 4 Jun 2024)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.26.2/debian/debuild-base/nginx-1.26.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
```
```
Linux *****.fastvps-server.com 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 GNU/Linux
```

### Description

When using ngx_stream_proxy_module with proxy_protocol on and ngx_http_realip_module with real_ip_header=proxy_protocol.

In the case **when a correct HTTP request is received**, the $remote_addr variable in the HTTP server logs is filled correctly - with the real IP of the user who accessed the proxy stream.

Example:
correct HTTP request: `curl -k https://***** -H "Content-Length: 0"`
in logs: `{"proxy_protocol_addr": "89.179.***.***", "proxy_protocol_port": "58064", "proxy_protocol_server_addr": "185.4.**.**", "proxy_protocol_server_port": "443", "remote_addr": "89.179.***.***", "status": "200", ...`
**This is OK**

If a **bad request is received**, the **$remote_addr variable is filled with the proxy address**, not the real client address, although as we can see from the $proxy_protocol_addr variable, nginx still receives the real address from the proxy.

Example:
invalid HTTP request, for example: `curl -k https://***** -H "Content-Length: bad header"`
in logs: `{"proxy_protocol_addr": "89.179.***.***", "proxy_protocol_port": "58065", "proxy_protocol_server_addr": "185.4.**.**", "proxy_protocol_server_port": "443", "remote_addr": "127.0.0.1", "status": "400", ...`
**This is not ok**. Why under the same conditions, $remote_addr = "127.0.0.1"

_This leads to the fact that in the logs we do not see the real IP of the user, especially when bots send incorrect requests, we can mistakenly take them for requests from the internal network when this is not the case. This is especially dangerous if we have configured permission rules for requests from 127.0.0.1 or from the local network._

#### nginx configuration

Stream configuration:
```
upstream https_upstream {
  server 127.0.0.1:444;
}

server {
  listen 443 default_server;
  listen [::]:443 default_server;
  
  ssl_preread on;
  proxy_protocol on;
  access_log off;
  
  proxy_pass https_upstream;
}
```
HTTP configuration:
```
server {
  listen 127.0.0.1:444 ssl proxy_protocol;
  real_ip_header proxy_protocol;
  set_real_ip_from 127.0.0.1;

  server_name *****;
  
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_buffering on;

  location / {
    proxy_pass http://backend-*****;
    proxy_http_version 1.1;
  }
}
```

**Comment by jo-carter** [comment]
@skl256 
This isn't a bug, request line & headers are fully processed and checked for validity (and the request rejected if not) prior to the POST_READ phase, where real_ip module runs (which populates $remote_addr with $proxy_protocol_addr).

> This leads to the fact that in the logs we do not see the real IP of the user, especially when bots send incorrect requests, we can mistakenly take them for requests from the internal network when this is not the case.

...It's in the logs in your example. For logging/visibility just use `$proxy_protocol_addr` instead of `$remote_addr`.

> This is especially dangerous if we have configured permission rules for requests from 127.0.0.1 or from the local network.

No further processing of the request (in terms of user configuration) by NGINX happens if request line & headers is malformed, as is the case in your example, so "permissions" (like the access module) are never reached in any case.
