### ISSUE TITLE
nginx 1.27.2 + boringssl-0.20241024.0

### ISSUE THREAD

**Issue by spacexnasa** [nginx/nginx#296]
almalinux 9.4

compile with boringssl,display this error message

./configure \
--prefix=/opt/nginx 
--with-http_v3_module \
--with-stream \
--with-stream_ssl_module \
--with-stream_realip_module \
--with-stream_ssl_preread_module \
--with-cc-opt="-I../boringssl/include" \
--with-ld-opt="-L../boringssl/build/ssl -L..//build/crypto"

src/event/quic/ngx_event_quic_openssl_compat.h:23:6: error: redeclaration of ‘enum ssl_encryption_level_t’
   23 | enum ssl_encryption_level_t {
      |      ^~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/ssl.h:3679:6: note: originally defined here
 3679 | enum ssl_encryption_level_t BORINGSSL_ENUM_INT {
      |      ^~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/quic/ngx_event_quic_connection.h:29,
                 from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_openssl_compat.h:24:5: error: redeclaration of enumerator ‘ssl_encryption_initial’
   24 |     ssl_encryption_initial = 0,
      |     ^~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/ssl.h:3680:3: note: previous definition of ‘ssl_encryption_initial’ with type ‘enum ssl_encryption_level_t’
 3680 |   ssl_encryption_initial = 0,
      |   ^~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/quic/ngx_event_quic_connection.h:29,
                 from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_openssl_compat.h:25:5: error: redeclaration of enumerator ‘ssl_encryption_early_data’
   25 |     ssl_encryption_early_data,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/ssl.h:3681:3: note: previous definition of ‘ssl_encryption_early_data’ with type ‘enum ssl_encryption_level_t’
 3681 |   ssl_encryption_early_data = 1,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/quic/ngx_event_quic_connection.h:29,
                 from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_openssl_compat.h:26:5: error: redeclaration of enumerator ‘ssl_encryption_handshake’
   26 |     ssl_encryption_handshake,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/ssl.h:3682:3: note: previous definition of ‘ssl_encryption_handshake’ with type ‘enum ssl_encryption_level_t’
 3682 |   ssl_encryption_handshake = 2,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/quic/ngx_event_quic_connection.h:29,
                 from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_openssl_compat.h:27:5: error: redeclaration of enumerator ‘ssl_encryption_application’
   27 |     ssl_encryption_application
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/ssl.h:3683:3: note: previous definition of ‘ssl_encryption_application’ with type ‘enum ssl_encryption_level_t’
 3683 |   ssl_encryption_application = 3,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/quic/ngx_event_quic_connection.h:29,
                 from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_openssl_compat.h:31:16: error: redefinition of ‘struct ssl_quic_method_st’
   31 | typedef struct ssl_quic_method_st {
      |                ^~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/ssl.h:3687:8: note: originally defined here
 3687 | struct ssl_quic_method_st {
      |        ^~~~~~~~~~~~~~~~~~
In file included from src/event/quic/ngx_event_quic_connection.h:29,
                 from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_openssl_compat.h:43:3: error: conflicting types for ‘SSL_QUIC_METHOD’; have ‘struct ssl_quic_method_st’
   43 | } SSL_QUIC_METHOD;
      |   ^~~~~~~~~~~~~~~
In file included from ../boringssl-0.20241024.0/include/openssl/ssl.h:145,
                 from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/base.h:374:35: note: previous declaration of ‘SSL_QUIC_METHOD’ with type ‘SSL_QUIC_METHOD’ {aka ‘struct ssl_quic_method_st’}
  374 | typedef struct ssl_quic_method_st SSL_QUIC_METHOD;
      |                                   ^~~~~~~~~~~~~~~
In file included from src/event/quic/ngx_event_quic_connection.h:29,
                 from src/event/quic/ngx_event_quic.c:10:
src/event/quic/ngx_event_quic_openssl_compat.h:48:5: error: conflicting types for ‘SSL_set_quic_method’; have ‘int(SSL *, const SSL_QUIC_METHOD *)’ {aka ‘int(struct ssl_st *, const struct ssl_quic_method_st *)’}
   48 | int SSL_set_quic_method(SSL *ssl, const SSL_QUIC_METHOD *quic_method);
      |     ^~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:17,
                 from src/core/ngx_core.h:85,
                 from src/event/quic/ngx_event_quic.c:8:
../boringssl-0.20241024.0/include/openssl/ssl.h:3801:20: note: previous declaration of ‘SSL_set_quic_method’ with type ‘int(SSL *, const SSL_QUIC_METHOD *)’ {aka ‘int(struct ssl_st *, const struct ssl_quic_method_st *)’}
 3801 | OPENSSL_EXPORT int SSL_set_quic_method(SSL *ssl,
      |                    ^~~~~~~~~~~~~~~~~~~
make[1]: *** [objs/Makefile:1143: objs/src/event/quic/ngx_event_quic.o] Error 1

**Comment by arut** [comment]
Just tried this BoringSSL version, everything went fine. Your output suggests nginx is trying to use OpenSSL compat layer for QUIC. This should not happen with BoringSSL since BoringSSL support the required API natively.

What if you remove `--with-http_v3_module`?

**Comment by spacexnasa** [comment]
> Just tried this BoringSSL version, everything went fine. Your output suggests nginx is trying to use OpenSSL compat layer for QUIC. This should not happen with BoringSSL since BoringSSL support the required API natively.
> 
> What if you remove `--with-http_v3_module`?

i need this parameter, the same compile parameter ?

**Comment by spacexnasa** [comment]
git clone https://github.com/google/boringssl && cd boringssl/
cmake -G Ninja -B build && ninja -C build



./configure \
--with-debug \
--with-cc-opt="-I$(pwd)/../boringssl/include" \
--with-ld-opt="-L$(pwd)/../boringssl/build/ssl -L$(pwd)/../boringssl/build/crypto" \
--prefix=/opt/nginx_with_boringssl \
--with-http_ssl_module \
--with-http_v2_module \
--with-http_v3_module \
--with-stream \
--with-stream_ssl_module \
--with-stream_realip_module \
--with-stream_ssl_preread_module \
--with-openssl=../boringssl

**Comment by spacexnasa** [comment]
if no --with-openssl=../boringssl then  in compile process, will display this error message

./configure: error: SSL modules require the OpenSSL library.
You can either do not enable the modules, or install the OpenSSL library
into the system, or build the OpenSSL library statically from the source
with nginx by using --with-openssl=<path> option.

if --with-openssl=../boringssl then 

Configuration summary
  + using system PCRE2 library
  + using OpenSSL library: ../boringssl
  + using system zlib library

  nginx path prefix: "/opt/nginx_boringssl"
  nginx binary file: "/opt/nginx_boringssl/sbin/nginx"
  nginx modules path: "/opt/nginx_boringssl/modules"
  nginx configuration prefix: "/opt/nginx_boringssl/conf"
  nginx configuration file: "/opt/nginx_boringssl/conf/nginx.conf"
  nginx pid file: "/opt/nginx_boringssl/logs/nginx.pid"
  nginx error log file: "/opt/nginx_boringssl/logs/error.log"
  nginx http access log file: "/opt/nginx_boringssl/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"


when exec make 


make -f objs/Makefile
make[1]: Entering directory '/home/software/nginx_boringssl/n/nginx-1.27.2'
cd ../boringssl \
&& if [ -f Makefile ]; then make clean; fi \
&& ./config --prefix=/home/software/nginx_boringssl/n/nginx-1.27.2/../boringssl/.openssl no-shared no-threads  \
&& make \
&& make install_sw LIBDIR=lib
/bin/sh: line 3: ./config: No such file or directory
make[1]: *** [objs/Makefile:1801: ../boringssl/.openssl/include/openssl/ssl.h] Error 127
make[1]: Leaving directory '/home/software/nginx_boringssl/n/nginx-1.27.2'
make: *** [Makefile:10: build] Error 2

**Comment by arut** [comment]
This line `../boringssl-0.20241024.0/include/openssl/ssl.h:3679:6: note: originally defined here` suggests that your compiler includes BoringSSL header from elsewhere, since this path is different from the one specified in `--with-cc-opt`.

**Comment by spacexnasa** [comment]
> This line `../boringssl-0.20241024.0/include/openssl/ssl.h:3679:6: note: originally defined here` suggests that your compiler includes BoringSSL header from elsewhere, since this path is different from the one specified in `--with-cc-opt`.

ok, thanks your advice, i will try later.

**Comment by willnode** [comment]
Hello, this happening to me to.

Closer inspection this all because of `NGX_QUIC_OPENSSL_COMPAT  1` defined.

It has this log

```
checking for OpenSSL QUIC support ... not found
checking for OpenSSL QUIC compatibility ... found
```

Here's repro build setup https://github.com/domcloud/nginx-builder/tree/3aedb1300c96e008d9f20ac627b3327a231d2130

**Comment by pluknet** [comment]
The `--with-openssl=` parameters is used to point to OpenSSL library sources only, see https://nginx.org/en/docs/configure.html for details.

To build against another OpenSSL-compatible library, such as BoringSSL, you are supposed either to install it to standard search paths or provide them by other means such as --with-cc-opt and --with-ld-opt.

**Comment by zpfhyj** [comment]
config params add  ”   --with-cc=c++ \
  --with-cc-opt='-I/data/soft/boringssl/include -x c' “
