### ISSUE TITLE
There is a memory leak in ngx_array_push

### ISSUE THREAD

**Issue by Shinylusir** [nginx/nginx#301]
void *
ngx_array_push(ngx_array_t *a)
{
    void        *elt, *new;
    size_t       size;
    ngx_pool_t  *p;

    if (a->nelts == a->nalloc) {

        /* the array is full */

        size = a->size * a->nalloc;

        p = a->pool;

        if ((u_char *) a->elts + size == p->d.last
            && p->d.last + a->size <= p->d.end)
        {
            p->d.last += a->size;
            a->nalloc++;

        } else {

            new = ngx_palloc(p, 2 * size);
            if (new == NULL) {
                return NULL;
            }

           /**
            *   WARNING:
            *  There is a memory leak.  
            *  When a->elts is overwritten by new, the memory in a->elts can no longer be used by others unless the memory pool is freed
          */
            ngx_memcpy(new, a->elts, size);
            a->elts = new; 
            a->nalloc *= 2; 
        }
    }

    elt = (u_char *) a->elts + a->size * a->nelts;
    a->nelts++;

    return elt;
}

**Comment by arut** [comment]
`ngx_array_push()` is not supposed to release old memory.  Most memory in nginx is allocated from a pool `ngx_pool_t` and is never released back to the pool. Instead, the entire pool is freed when the entity it's associated with (`ngx_connection_t`, `ngx_http_request_t` etc) is destroyed. See https://nginx.org/en/docs/dev/development_guide.html#pool for more details.
