### ISSUE TITLE
proxy_set_header is under-documented: need to improve the proxy_set_header documentation to make sure nginx discards the web client's header value & sets the new specified value

### ISSUE THREAD

**Issue by tattwamasii2p** [nginx/nginx#323]
### Environment

Documentation issue. The current English version of the page http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header is incomplete.

  - `nginx -V`

All/any.

  - `uname -a`

All/any.

### Description

Nginx is under-documented.
Does nginx's proxy_set_header delete the header value coming from web client when modifying the header value to proxy_set_header's second argument (i.e. to the argument <i>value</i> at "Syntax" line at http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header )? This is not specified by nginx documentation.

Actual: no docs of how to make sure nginx strips the web client request header value.

Expected: documented way to specify that non-empty value must override the header value & discard the web client's header value.

For the use case where it's needed, see 

 * https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-SECURE_PROXY_SSL_HEADER and
 * https://docs.djangoproject.com/en/5.1/ref/settings/#secure-ssl-redirect .

- [v] The bug is reproducible with the latest version of nginx documentation;
- [v] The nginx configuration is minimized to the smallest possible to reproduce the issue and doesn't contain third-party modules.

#### nginx configuration

```
server {
    # ...
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    # ...
    location / {
       uwsgi_pass unix:///var/www/logs-srv/logs-srv.sock;
       # ...
       proxy_set_header X-Forwarded-Proto $scheme;
   }
}
```

#### nginx debug log

N/A

**Comment by nanaya** [comment]
"Allows redefining or appending fields to the request header to the proxied server" from the first sentence of the documentation aside, `proxy_*` directives don't do anything when using `uwsgi`. Maybe try [`uwsgi_param`](https://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_param) instead?

**Comment by tattwamasii2p** [comment]
How to make sure that `uwsgi_param`'s `value` is not appended to the request header value? Or `uwsgi_param` doesn't deal with http[s] request headers? Where is that specified in docs?

I currently have 

```txt
        location / {
            uwsgi_pass unix:///var/www/logs-srv/logs-srv.sock;
            include /etc/nginx/uwsgi_params; #Specify your actual directory.
            uwsgi_param UWSGI_SCRIPT /home/user/vcs/telemetry-host2/telemetry_host_django/wsgi.py; #Specify your actual directory.
            uwsgi_param UWSGI_CHDIR /home/user/vcs/telemetry-host2; #Specify your actual directory.
            index  index.html index.htm;
            client_max_body_size 35m;
            index index.html index.htm;

            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_redirect off;
            proxy_buffer_size 32k;
            proxy_buffers 4 32k;
       }
```

All of proxy_* should probably be removed and *_set_header replaced by uwsgi_param

`/etc/nginx/uwsgi_params` is:
```txt
uwsgi_param  QUERY_STRING       $query_string;
uwsgi_param  REQUEST_METHOD     $request_method;
uwsgi_param  CONTENT_TYPE       $content_type;
uwsgi_param  CONTENT_LENGTH     $content_length;

uwsgi_param  REQUEST_URI        $request_uri;
uwsgi_param  PATH_INFO          $document_uri;
uwsgi_param  DOCUMENT_ROOT      $document_root;
uwsgi_param  SERVER_PROTOCOL    $server_protocol;
uwsgi_param  REQUEST_SCHEME     $scheme;
uwsgi_param  HTTPS              $https if_not_empty;

uwsgi_param  REMOTE_ADDR        $remote_addr;
uwsgi_param  REMOTE_PORT        $remote_port;
uwsgi_param  SERVER_PORT        $server_port;
uwsgi_param  SERVER_NAME        $server_name;
```

**Comment by tattwamasii2p** [comment]
Closing as Invalid. Need to read the full nginx docs, particularly on uwsgi module.
