### ISSUE TITLE
Missing quote in string

### ISSUE THREAD

**Issue by ericwhitmansmith** [nginx/nginx#330]
There seems to be a missing double quote in a string in src/event/ngx_event_openssl.c. Specifically, this line:

                      "SSL_CTX_set0_tmp_dh_pkey(\%s\") failed", file->data);

should probably be this (added a double quote before the percent sign):

                      "SSL_CTX_set0_tmp_dh_pkey(\"%s\") failed", file->data);

The original string has the nonstandard escape \%, and it seems quite clear by looking at other strings in the file that the intent was to write \"%.

**Comment by Maryna-f5** [comment]
Thank you, @ericwhitmansmith, for reporting this issue! 

This is the fix https://github.com/nginx/nginx/pull/339
