### ISSUE TITLE
New SSL/TLS Version Macro Inverted?

### ISSUE THREAD

**Issue by tmcqueen-materials** [nginx/nginx#350]
This is a code review question. In the latest (as of writing) commit, a new macro was added to help set TLS version numbers. The newly added lines:
https://github.com/nginx/nginx/blob/476d6526b2e8297025c608425f4cad07b4f65990/src/event/ngx_event_openssl.h#L190-L194
appear to enable TLSv1.0 and TLSv1.1 by default if neither `SSL_OP_NO_TLSv1_2` or `SSL_OP_NO_TLSv1_3` is set. This is opposite to the behavior of the code segments this macro replaces... I believe it should be replaced with something like:
```c
 #if (defined SSL_OP_NO_TLSv1_2 && defined SSL_OP_NO_TLSv1_3) 
 #define NGX_SSL_DEFAULT_PROTOCOLS  (NGX_SSL_TLSv1|NGX_SSL_TLSv1_1) 
 #else 
 #define NGX_SSL_DEFAULT_PROTOCOLS  (NGX_SSL_TLSv1_2|NGX_SSL_TLSv1_3) 
 #endif 
```
Which enables TLSv1.2 and TLSv1.3 if at least one is available, enabling TLSv1.0/1.1 only if neither 1.2 or 1.3 is available.

If I'm wrong, of course just close this issue. Thanks for the wonderful program!

**Comment by arut** [comment]
`SSL_OP_NO_TLSv1_2` and `SSL_OP_NO_TLSv1_3` macros are used as indicators that TLSv1.2 and TLSv1.3 are supported by the library.
