### ISSUE TITLE
http special response format incomplete

### ISSUE THREAD

**Issue by wohaiaini** [nginx/nginx#352]
There are several code as follows below, lack of  "\</hr>" to complete "\<hr>":
in http special response and autoindex module， I wonder whether it's a problem or not ,
but when it's parsed without \</hr>, some 3rd party may cause problems, e.g., memory leak ...

1.
```
static u_char ngx_http_error_tail[] =
"<hr><center>nginx</center>" CRLF
"</body>" CRLF
"</html>" CRLF
;
```

which should be 
```
static u_char ngx_http_error_tail[] =
"<hr><center>nginx</center></hr>" CRLF
"</body>" CRLF
"</html>" CRLF
;
```

2.
```
static u_char ngx_http_error_full_tail[] =
"<hr><center>" NGINX_VER "</center>" CRLF
"</body>" CRLF
"</html>" CRLF
;
```

3.
```
static u_char ngx_http_error_build_tail[] =
"<hr><center>" NGINX_VER_BUILD "</center>" CRLF
"</body>" CRLF
"</html>" CRLF
```

**Comment by HanadaLee** [comment]
This HTML tag does not need `</hr>`. If you add `</hr>` to it, it will be wrong.

**Comment by wohaiaini** [comment]
Thanks.
