### ISSUE TITLE
Client does not receive the full certificate chain

### ISSUE THREAD

**Issue by izanami-01** [nginx/nginx#365]
### Description

When providing SSL/TLS certificates to nginx server, only the server certificate (tls.crt) is typically provided. However, to ensure that clients can verify the server certificate’s trust, the full certificate chain is needed, which includes both the server certificate and the intermediate CA certificates (ca.crt). In many cases, the intermediate certificates are not automatically appended to the server certificate ( nginx ingress-controller), causing issues with certificate validation.
I'm using self-signed SSL certificate, and manually appended the server certificate and the intermediate certificates but  the client does not receive the full certificate chain.

Could you suggest a workaround or anything missing here ?

**Comment by yangyinmiao** [comment]
Perhaps you can check whether the configured ssl_verify_depth matches the depth of your certificate.

**Comment by izanami-01** [comment]
The concatenated server certificate and intermediate certificate is the WA, just that I had to use `-showcerts` flag with openssl command:
`openssl s_client -connect <ip:port> -CAfile rootCA.crt -showcerts`
