### ISSUE TITLE
nginx: 1.26.2 using HTTP/2 without SSL, i don't known how to configure

### ISSUE THREAD

**Issue by wwwhaoxu** [nginx/nginx#396]
### Environment

Include the result of the following commands:
  - `nginx -V`
      nginx: 1.26.2
  
  - `uname -a`
      Linux 6.1.119-129.201.amzn2023.x86_64 #1SMP PREEMPT_DYNAMIC Tue Dec 3 21:07:35 UTC2024 x86_64 x86_64 x86_64 GNU/Linux

### Description

nginx: 1.26.2 using HTTP/2 without SSL, i don't known how to configure

#### nginx configuration

```
server {
    listen 80; 
    server_name localhost;
    http2 on;

    location / {
       return 200 "OK";
    }
}
```
or share the configuration in [gist](https://gist.github.com/).

#### nginx test output
curl --http2 127.0.0.1 -I
HTTP/1.1 200 OK

Server: nginx/1.26.2
Date: Thu, 19 Dec 2024 03:10:37 GMT
Content-Type: application/octet-stream
Content-Length: 2
Connection: keep-alive

**Comment by lcrilly** [comment]
Please use [Discussions](https://github.com/nginx/nginx/discussions) for configuration questions.

Your config is fine. You are not using your HTTP client correctly. Try with `curl --http2-prior-knowledge`. See:
```shell
man curl | grep -A20 -- --http2-prior-knowledge
```

**Comment by wwwhaoxu** [comment]
@lcrilly , thanks, The problem has been solved using the method you provided.
