### ISSUE TITLE
directives ssl_ciphers and proxy_ssl_ciphers doesn't work with ssl_protocols TLSv1.3;

### ISSUE THREAD

**Issue by khabibulinmi** [nginx/nginx#410]
### Environment

Include the result of the following commands:
  - `nginx -V`
  1.24
  - `uname -a`
Linux 1a91f4bbe39b 6.6.32-linuxkit #1 SMP PREEMPT_DYNAMIC Thu Jun 13 14:14:43 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
### Description
**Synopsys: you can't choose cipher with TLSv1.3 right now**
directives ssl_ciphers and proxy_ssl_ciphers doesn't work with ssl_protocols TLSv1.3;
consider:
https://docs.openssl.org/master/man3/SSL_CTX_set_cipher_list/#synopsis

**SSL_set_cipher_list**() sets the list of ciphers (**TLSv1.2** and **below**) only for ssl.
for TLSv1.3 you should use **SSL_CTX_set_ciphersuites**() 

in function ngx_ssl_ciphers is used command for tls1.2
changing it from SSL_set_cipher_list to SSL_CTX_set_ciphersuites solves the problem for work with tls1.3.
https://github.com/nginx/nginx/blob/stable-1.26/src/event/ngx_event_openssl.c#L887

launching nginx with bellow config will print
[emerg] SSL_CTX_set_cipher_list("TLS_AES128-GCM-SHA256") failed (SSL: error:1426E0B9:SSL routines:ciphersuite_cb:no cipher match)
Problem solves quite easy by adding extra directive for list of ciphers for TLS1 1.3
ex: 
ssl_protocols TLSv1.3;
ssl_ciphers_**tls** TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256;
ssl_ciphers_**tls** - because ciphers in TLS 1.3 starts with TSL

- [x] The bug is reproducible with the latest version of nginx
yep, it will
- [x] The nginx configuration is minimized to the smallest possible
to reproduce the issue and doesn't contain third-party modules
yep

#### nginx configuration

```
# Your nginx configuration here
error_log /opt/nginx/logs/error.log;
daemon off;
master_process off;
# worker_processes 1;

events {}

http {
    ssl_certificate /home/nginx/ssl/server.crt;
    ssl_certificate_key /home/nginx/ssl/server.key;
    ssl_protocols TLSv1.3;
    ssl_ciphers TLS_AES_128_GCM_SHA256;
    proxy_ssl_ciphers TLS_AES_128_GCM_SHA256;

    log_format main '$ssl_cipher $remote_addr - $remote_user [$time_local] "$request"'
        '$status $body_bytes_sent "$http_referer"'
        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /opt/nginx/logs/access.log main;

    upstream firstMock {
        server 127.0.0.2:10001;
    }

    server {
        listen 10000 ssl;
        location / {
            proxy_pass https://firstMock;
        }
    }
}
```
or share the configuration in [gist](https://gist.github.com/).

#### nginx debug log

It is advised to enable
[debug logging](http://nginx.org/en/docs/debugging_log.html).
```
# Your nginx debug log here
```
or share the debug log in [gist](https://gist.github.com/).

**Comment by pluknet** [comment]
We do not consider adding TLSv1.3 ciphers support for these directives.
Rather the underlying library should support this.
Meanwhile you can use the ssl_conf_command directive for this purpose.

See for details: https://trac.nginx.org/nginx/ticket/1529

**Comment by khabibulinmi** [comment]
Correct the documentation, not a word that this directive does not support TLS 1.3
